{"name": "test_fixture_scope_function01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 96 > 100", "trace": "random_num = 96\n\n    @allure.feature(\"test_02_fixture\")\n    @allure.story(\"scope\")\n    def test_fixture_scope_function01(random_num):\n        print(f'random_num: {random_num}')\n>       assert random_num > 100\nE       assert 96 > 100\n\ntest_02_fixture_for_allure.py:121: AssertionError"}, "start": 1627036713388, "stop": 1627036713388, "uuid": "d534cbd1-553a-422f-902e-49e46a013644", "historyId": "541b59f09b5a50b681f45afbfa986c33", "testCaseId": "e06d2c0c803f299dd3fb695682f833cf", "fullName": "test_02_fixture_for_allure#test_fixture_scope_function01", "labels": [{"name": "feature", "value": "test_02_fixture"}, {"name": "story", "value": "scope"}, {"name": "suite", "value": "test_02_fixture_for_allure"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "11292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_fixture_for_allure"}]}