{"name": "test_01", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1 == 2\n  +1\n  -2", "trace": "self = <test_demo.test_03_mark_for_allure.TestMark object at 0x00000287F82B9CC8>\n\n    @allure.story(\"story: story in class\")\n    @pytest.mark.xfail(raises=AssertionError)\n    def test_01(self):\n>       assert 1 == 2\nE       assert 1 == 2\nE         +1\nE         -2\n\ntest_03_mark_for_allure.py:60: AssertionError"}, "start": 1627038117186, "stop": 1627038117186, "uuid": "060cbada-45fb-4194-9aff-36c121870e19", "historyId": "2e8991d41404440dd62ad3011af1ef9d", "testCaseId": "c32d2da15a0e7bbc68d15cdf17985f5e", "fullName": "test_03_mark_for_allure.TestMark#test_01", "labels": [{"name": "story", "value": "story: story in class"}, {"name": "feature", "value": "feature: test_03_mark, feature mark at class level"}, {"name": "tag", "value": "@pytest.mark.xfail(raises=<class 'AssertionError'>)"}, {"name": "suite", "value": "test_03_mark_for_allure"}, {"name": "subSuite", "value": "TestMark"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "18748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_03_mark_for_allure"}]}