{"name": "test_fixture_scope_function01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 44 > 100", "trace": "random_num = 44\n\n    @allure.feature(\"feature: test_02_fixture\")\n    @allure.story(\"story: scope\")\n    def test_fixture_scope_function01(random_num):\n        print(f'random_num: {random_num}')\n>       assert random_num > 100\nE       assert 44 > 100\n\ntest_02_fixture_for_allure.py:121: AssertionError"}, "start": 1627038702470, "stop": 1627038702470, "uuid": "53353c45-5a91-477f-9988-0e80ca70cd53", "historyId": "541b59f09b5a50b681f45afbfa986c33", "testCaseId": "e06d2c0c803f299dd3fb695682f833cf", "fullName": "test_02_fixture_for_allure#test_fixture_scope_function01", "labels": [{"name": "story", "value": "story: scope"}, {"name": "feature", "value": "feature: test_02_fixture"}, {"name": "suite", "value": "test_02_fixture_for_allure"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "19824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_fixture_for_allure"}]}