{"name": "test_01", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 1 == 2\n  +1\n  -2", "trace": "@pytest.mark.xfail(raises=AssertionError)\n    def test_01():\n>       assert 1 == 2\nE       assert 1 == 2\nE         +1\nE         -2\n\ntest_03_mark.py:53: AssertionError"}, "start": 1627038117074, "stop": 1627038117075, "uuid": "cff8925f-62d2-4ebb-b063-75198f1862e2", "historyId": "b73719d8f7656361eefb6ee834731880", "testCaseId": "ac37dbbf112537bc8c7ae0451e904306", "fullName": "test_03_mark#test_01", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(raises=<class 'AssertionError'>)"}, {"name": "suite", "value": "test_03_mark"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "18748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_03_mark"}]}