{"name": "test_02", "status": "broken", "statusDetails": {"message": "TypeError: 传入参数非整数", "trace": "@pytest.mark.xfail(raises=ValueError)\n    def test_02():\n        if isinstance('1234', int) is not True:\n>           raise TypeError(\"传入参数非整数\")\nE           TypeError: 传入参数非整数\n\ntest_03_mark.py:59: TypeError"}, "start": 1627036719234, "stop": 1627036719234, "uuid": "30d360f9-cd95-46f3-8a4c-0d9abd7fbc21", "historyId": "071c228f4b696c4abcee8b4e6506c70e", "testCaseId": "025cfa94ad170b96219dbcd77de24178", "fullName": "test_03_mark#test_02", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(raises=<class 'ValueError'>)"}, {"name": "suite", "value": "test_03_mark"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "11292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_03_mark"}]}