{"name": "test_fixture_scope_function02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 72 > 100", "trace": "random_num = 72\n\n    def test_fixture_scope_function02(random_num):\n        print(f'random_num: {random_num}')\n>       assert random_num > 100\nE       assert 72 > 100\n\ntest_02_fixture.py:60: AssertionError"}, "start": 1627037543627, "stop": 1627037543627, "uuid": "5f463175-b619-4a39-8d45-fe41bddc0aef", "historyId": "40cc6378bf49404693017b0e13f6ddf6", "testCaseId": "c070a04923b6c70944d2180706a90f72", "fullName": "test_02_fixture#test_fixture_scope_function02", "labels": [{"name": "suite", "value": "test_02_fixture"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "4280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_fixture"}]}