{"name": "test_fixture_scope_module01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 14 < 10", "trace": "ramdom_int_in_module = 14\n\n    def test_fixture_scope_module01(ramdom_int_in_module):\n>       assert ramdom_int_in_module < 10\nE       assert 14 < 10\n\ntest_02_fixture.py:45: AssertionError"}, "start": 1627037543539, "stop": 1627037543539, "uuid": "30826138-c734-46bf-9e8b-3ac0658f8e70", "historyId": "a35e67ee532c6b01bb1d805fd977ac3e", "testCaseId": "c7b17272c4c84bd0eb9dd77ecaa46c3f", "fullName": "test_02_fixture#test_fixture_scope_module01", "labels": [{"name": "suite", "value": "test_02_fixture"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "4280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_fixture"}]}