{"name": "test_fixture_scope_function02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 41 > 100", "trace": "random_num = 41\n\n    @allure.feature(\"test_02_fixture\")\n    @allure.story(\"scope\")\n    def test_fixture_scope_function02(random_num):\n        print(f'random_num: {random_num}')\n>       assert random_num > 100\nE       assert 41 > 100\n\ntest_02_fixture_for_allure.py:128: AssertionError"}, "start": 1627037551956, "stop": 1627037551956, "uuid": "f85f7076-9e36-4776-bf62-f515fa281025", "historyId": "bc793ffa39f480a6e531b46edd1f566b", "testCaseId": "9a54bb79dd6497bb4fcb3429e98858cf", "fullName": "test_02_fixture_for_allure#test_fixture_scope_function02", "labels": [{"name": "story", "value": "scope"}, {"name": "feature", "value": "test_02_fixture"}, {"name": "suite", "value": "test_02_fixture_for_allure"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "4280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02_fixture_for_allure"}]}