{"name": "test_mark_xfail", "status": "skipped", "statusDetails": {"message": "XFAIL comments\n\nAssertionError: assert 0 == 1\n  +0\n  -1", "trace": "self = <test_demo.test_03_mark_for_allure.TestMark object at 0x000001EB908495C8>\n\n    @allure.story(\"story in class\")\n    @pytest.mark.xfail(condition=(5>1),reason = \"comments\")\n    def test_mark_xfail(self):\n>       assert 0 == 1\nE       assert 0 == 1\nE         +0\nE         -1\n\ntest_03_mark_for_allure.py:55: AssertionError"}, "start": 1627036719301, "stop": 1627036719301, "uuid": "863d9a0a-7157-4db3-ac4c-cb92dce80bdf", "historyId": "6ff681866bbf8e51212eac6d94b27f7a", "testCaseId": "e95014108faa9ab09ce62758c639d0cc", "fullName": "test_03_mark_for_allure.TestMark#test_mark_xfail", "labels": [{"name": "story", "value": "story in class"}, {"name": "feature", "value": "test_03_mark, feature mark at class level"}, {"name": "tag", "value": "@pytest.mark.xfail(condition=True, reason='comments')"}, {"name": "suite", "value": "test_03_mark_for_allure"}, {"name": "subSuite", "value": "TestMark"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "11292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_03_mark_for_allure"}]}