{"name": "test_mark_xfail", "status": "skipped", "statusDetails": {"message": "XFAIL comments\n\nAssertionError: assert 0 == 1\n  +0\n  -1", "trace": "@pytest.mark.xfail(condition=(5>1),reason = \"comments\")\n    def test_mark_xfail():\n>       assert 0 == 1\nE       assert 0 == 1\nE         +0\nE         -1\n\ntest_03_mark.py:48: AssertionError"}, "start": 1627037557284, "stop": 1627037557284, "uuid": "c05be63a-fcb6-426f-9af3-a8388d1e01f3", "historyId": "964ddb174184766374ab4bd61fc8b713", "testCaseId": "ee90e73412a9ef6ce0f4d5964726e709", "fullName": "test_03_mark#test_mark_xfail", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(condition=True, reason='comments')"}, {"name": "suite", "value": "test_03_mark"}, {"name": "host", "value": "JULIZHOU-6JV5P"}, {"name": "thread", "value": "4280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_03_mark"}]}